//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/TouchControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchControls"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""8f1b997b-4acf-4df5-b224-0366ebd40618"",
            ""actions"": [
                {
                    ""name"": ""Touch_Input"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b60d40ad-ab54-4265-8d2a-0915e5bccf06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch_Pressed"",
                    ""type"": ""PassThrough"",
                    ""id"": ""27689164-dcad-4bfd-b28e-ff436ed9db21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch_Pos"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bb16f948-ef9b-42de-90b9-06cfa3ae2f0c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3fb4473a-c38f-44cb-8c54-dff10a67463c"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ea9f1d4-7f35-4662-acd2-7d3bd3f7b64b"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch_Input"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""993b0f71-115b-41b1-84f3-27f6abaab221"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch_Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_Touch_Input = m_Touch.FindAction("Touch_Input", throwIfNotFound: true);
        m_Touch_Touch_Pressed = m_Touch.FindAction("Touch_Pressed", throwIfNotFound: true);
        m_Touch_Touch_Pos = m_Touch.FindAction("Touch_Pos", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_Touch_Touch_Input;
    private readonly InputAction m_Touch_Touch_Pressed;
    private readonly InputAction m_Touch_Touch_Pos;
    public struct TouchActions
    {
        private @TouchControls m_Wrapper;
        public TouchActions(@TouchControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touch_Input => m_Wrapper.m_Touch_Touch_Input;
        public InputAction @Touch_Pressed => m_Wrapper.m_Touch_Touch_Pressed;
        public InputAction @Touch_Pos => m_Wrapper.m_Touch_Touch_Pos;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @Touch_Input.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Input;
                @Touch_Input.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Input;
                @Touch_Input.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Input;
                @Touch_Pressed.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Pressed;
                @Touch_Pressed.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Pressed;
                @Touch_Pressed.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Pressed;
                @Touch_Pos.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Pos;
                @Touch_Pos.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Pos;
                @Touch_Pos.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouch_Pos;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Touch_Input.started += instance.OnTouch_Input;
                @Touch_Input.performed += instance.OnTouch_Input;
                @Touch_Input.canceled += instance.OnTouch_Input;
                @Touch_Pressed.started += instance.OnTouch_Pressed;
                @Touch_Pressed.performed += instance.OnTouch_Pressed;
                @Touch_Pressed.canceled += instance.OnTouch_Pressed;
                @Touch_Pos.started += instance.OnTouch_Pos;
                @Touch_Pos.performed += instance.OnTouch_Pos;
                @Touch_Pos.canceled += instance.OnTouch_Pos;
            }
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnTouch_Input(InputAction.CallbackContext context);
        void OnTouch_Pressed(InputAction.CallbackContext context);
        void OnTouch_Pos(InputAction.CallbackContext context);
    }
}
